# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vat_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online_shop', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=125)),
                ('zip_code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('test1', models.CharField(max_length=50)),
                ('commission_rate', models.IntegerField(default=50)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
