# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='test1',
        ),
        migrations.AddField(
            model_name='store',
            name='shipping_agrement',
            field=models.CharField(blank=True, choices=[(b'store_pays', b'Store pays shippings costs'), (b'split', b'Shipping costs are split'), (b'we_pay', b'We pay shipping costs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='vat_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='store',
            name='commission_rate',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
