# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
                ('recipient', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=125)),
                ('zip_code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=250)),
                ('tax_number', models.CharField(blank=True, max_length=250)),
                ('country', models.ForeignKey(blank=True, to='api.Country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='store',
            name='invoice_address',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Invoice_address'),
        ),
    ]
