# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170106_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.CharField(blank=True, choices=[(b'eu28', b'EU28'), (b'efta', b'EFTA')], max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='partner_type',
            field=models.CharField(blank=True, choices=[(b'commission', b'Commission'), (b'direct_buyer', b'Direct buyer'), (b'mixed', b'Mixed')], max_length=20),
        ),
    ]
