# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_field_invoice_to_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[(b'DE', b'German'), (b'EN', b'English')], default=b'DE', max_length=2)),
                ('partner_type', models.CharField(choices=[(b'seller', b'Seller'), (b'producer', b'Producer'), (b'agency', b'Agent'), (b'other', b'Other')], default=b'seller', max_length=25)),
                ('gender', models.CharField(choices=[(b'F', b'Female'), (b'M', b'Male')], default=b'F', max_length=1)),
                ('given_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_1', models.CharField(blank=True, max_length=50)),
                ('phone_2', models.CharField(blank=True, max_length=50)),
                ('email_1', models.EmailField(blank=True, max_length=50)),
                ('email_2', models.EmailField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('given_name', 'surname'),
            },
        ),
        migrations.AlterModelOptions(
            name='invoice_address',
            options={'ordering': ('recipient',)},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='invoice_address',
            name='name',
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='store',
            name='pinterest',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='store',
            name='shipping_agrement',
            field=models.CharField(blank=True, choices=[(b'store_pays', b'Store pays shippings costs'), (b'split', b'Shipping costs are split'), (b'we_pay', b'We pay shipping costs')], default=b'split', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='invoice_address',
            name='contact_person',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_person',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
