# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170106_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, choices=[(b'eur', b'Euro'), (b'gbp', b'British Pound'), (b'cad', b'Canadian Dollar'), (b'dkk', b'Danish Krone'), (b'nok', b'Norwegian Krone'), (b'rub', b'Russian Rubel'), (b'sek', b'Swedish Krona'), (b'chf', b'Swiss Franken'), (b'usd', b'US Dollar')], max_length=3),
        ),
    ]
