# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170107_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='contact_person',
        ),
    ]
