# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170107_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=125)),
                ('addition_to_address', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact_person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'ordering': ('recipient',),
            },
        ),
    ]
