# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shipping_address',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Shipping_address'),
        ),
    ]
