# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('correction_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfref', to='api.Packing_list')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Packing list',
                'verbose_name_plural': 'Packing lists',
            },
        ),
        migrations.AddField(
            model_name='product_move',
            name='packing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packinglist', to='api.Packing_list'),
        ),
    ]
