# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170129_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_move',
            name='packing_list',
        ),
        migrations.AlterField(
            model_name='product_move',
            name='move_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moveto', to='api.Store', verbose_name=b'Move to store'),
        ),
    ]
