# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170129_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing_list',
            name='product_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productmoveref', to='api.Product_move'),
        ),
        migrations.AlterField(
            model_name='packing_list',
            name='correction_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfref', to='api.Packing_list'),
        ),
    ]
