# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170107_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to=b'images')),
                ('perspective', models.CharField(blank=True, choices=[(b'front', b'Front'), (b'side', b'Side'), (b'back', b'Back'), (b'detail', b'Detail')], max_length=10)),
                ('photographer', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('target_group', models.CharField(choices=[(b'women', b'Women'), (b'men', b'Men'), (b'unisex', b'unisex')], default=b'unisex', max_length=6)),
                ('description_de', models.TextField(blank=True, max_length=500, verbose_name=b'German description')),
                ('description_en', models.TextField(blank=True, max_length=500, verbose_name=b'English description')),
                ('description_it', models.TextField(blank=True, max_length=500, verbose_name=b'Italian description')),
            ],
            options={
                'ordering': ('-name',),
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Product_variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_organic', models.BooleanField(default=False, verbose_name=b'Organic')),
                ('name_en', models.CharField(max_length=50, verbose_name=b'English name')),
                ('name_de', models.CharField(blank=True, max_length=50, verbose_name=b'German name')),
                ('name_it', models.CharField(blank=True, max_length=50, verbose_name=b'Italian name')),
                ('description_de', models.TextField(blank=True, max_length=500, verbose_name=b'German description')),
                ('description_en', models.TextField(blank=True, max_length=500, verbose_name=b'English description')),
                ('description_it', models.TextField(blank=True, max_length=500, verbose_name=b'Italian description')),
                ('care_instructions_de', models.TextField(blank=True, max_length=250, verbose_name=b'German care instructions')),
                ('care_instructions_en', models.TextField(blank=True, max_length=250, verbose_name=b'English care instructions')),
                ('care_instructions_it', models.TextField(blank=True, max_length=250, verbose_name=b'Italian care instructions')),
                ('rec_gross_sale_price_default', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name=b'Recommended default gross sale price')),
                ('size', models.CharField(blank=True, choices=[(b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL'), (b'ws', b'Women S'), (b'wxs', b'Women XS'), (b'wm', b'Women M'), (b'wl', b'Women L'), (b'wxl', b'Women XL'), (b'ms', b'Men S'), (b'mxs', b'Men XS'), (b'mm', b'Men M'), (b'ml', b'Men L'), (b'mxl', b'Men XL'), (b'mxxl', b'Men XXL')], default=b'm', max_length=6)),
                ('color_1', models.CharField(max_length=50, verbose_name=b'Main color')),
                ('color_2', models.CharField(blank=True, max_length=50, verbose_name=b'2nd color')),
                ('color_3', models.CharField(blank=True, max_length=50, verbose_name=b'3rd color')),
                ('color_4', models.CharField(blank=True, max_length=50, verbose_name=b'4th color')),
                ('fabric_1', models.CharField(max_length=50, verbose_name=b'Main fabric')),
                ('fabric_2', models.CharField(blank=True, max_length=50, verbose_name=b'2nd fabric')),
                ('fabric_3', models.CharField(blank=True, max_length=50, verbose_name=b'3rd fabric')),
                ('fabric_4', models.CharField(blank=True, max_length=50, verbose_name=b'4th fabric')),
                ('fabric_1_percentage', models.IntegerField(blank=True, default=100, help_text=b'Percentage of the main fabric in %', verbose_name=b'Percentage main fabric')),
                ('fabric_2_percentage', models.IntegerField(blank=True, help_text=b'Percentage of 2nd fabric in %', verbose_name=b'Percentage 2nd fabric')),
                ('fabric_3_percentage', models.IntegerField(blank=True, help_text=b'Percentage of 3rd fabric in %', verbose_name=b'Percentage 3rd fabric')),
                ('fabric_4_percentage', models.IntegerField(blank=True, help_text=b'Percentage of 4th fabric in %', verbose_name=b'Percentage 4th fabric')),
                ('weight', models.SmallIntegerField(blank=True, help_text=b'Product weight in grams')),
                ('surface_weight', models.SmallIntegerField(blank=True, help_text=b'Product surface weight in grams/m\xc2\xb2')),
            ],
            options={
                'ordering': ('-name_en',),
                'verbose_name': 'Product variant',
                'verbose_name_plural': 'Product variants',
            },
        ),
        migrations.AlterField(
            model_name='store',
            name='commission_rate',
            field=models.IntegerField(blank=True, default=50, help_text=b'Commmission as charged by the store in %'),
        ),
    ]
