# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170129_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.CharField(blank=True, choices=[(b'paid', b'Paid'), (b'open', b'Open'), (b'chancelled', b'Chancelled')], default=b'open', max_length=20)),
                ('discount_description', models.TextField(blank=True, null=True)),
                ('discount_amount', models.IntegerField(blank=True, default=0, help_text=b'Discount amount as a positive number', null=True)),
                ('correction_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfref', to='api.Invoice')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Invoice'),
        ),
    ]
