# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
    ]
