# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_variant_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='fabric_2_percentage',
            field=models.IntegerField(blank=True, default=0, help_text=b'Percentage of 2nd fabric in %', verbose_name=b'Percentage 2nd fabric'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='fabric_3_percentage',
            field=models.IntegerField(blank=True, default=0, help_text=b'Percentage of 3rd fabric in %', verbose_name=b'Percentage 3rd fabric'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='fabric_4_percentage',
            field=models.IntegerField(blank=True, default=0, help_text=b'Percentage of 4th fabric in %', verbose_name=b'Percentage 4th fabric'),
        ),
    ]
