# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170129_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='product_move',
            name='sale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sale'),
        ),
    ]
