# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170219_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_move',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product_move'),
        ),
    ]
