# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170107_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='rec_gross_sale_price_default',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name=b'Recommended default gross sale price'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='surface_weight',
            field=models.SmallIntegerField(blank=True, default=0, help_text=b'Product surface weight in grams/m\xc2\xb2'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='weight',
            field=models.SmallIntegerField(blank=True, default=0, help_text=b'Product weight in grams'),
        ),
    ]
