# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170219_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_move',
            name='is_destroyed',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_destroyed',
            field=models.BooleanField(default=False, help_text=b'Mark products(s) as destroyed, stolen or otherwise non-saleable', verbose_name=b'Destroyed?'),
        ),
    ]
