# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170109_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(b'coat', b'Coat'), (b'dress', b'Dress'), (b'jacket', b'Jacket'), (b'longsleeve', b'Longsleeve'), (b'pullover', b'Pullover'), (b'shirt', b'Shirt'), (b'skirt', b'Skirt'), (b'trousers', b'Trousers'), (b'other', b'Other')], default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_variant',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='is_organic',
            field=models.BooleanField(default=False, help_text=b'Is this product variant made from organic materials?', verbose_name=b'Organic'),
        ),
    ]
