# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170109_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_variant',
            options={'ordering': ('created',), 'verbose_name': 'Product variant', 'verbose_name_plural': 'Product variants'},
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='name_it',
        ),
    ]
