# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170109_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='size',
            field=models.CharField(choices=[(b'unisize', b'Unisize'), (b's', b'S'), (b'xs', b'XS'), (b'm', b'M'), (b'l', b'L'), (b'xl', b'XL'), (b'xxl', b'XXL'), (b'ws', b'Women S'), (b'wxs', b'Women XS'), (b'wm', b'Women M'), (b'wl', b'Women L'), (b'wxl', b'Women XL'), (b'ms', b'Men S'), (b'mxs', b'Men XS'), (b'mm', b'Men M'), (b'ml', b'Men L'), (b'mxl', b'Men XL'), (b'mxxl', b'Men XXL')], default=b'unisize', max_length=7),
        ),
    ]
