# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170109_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online_shop', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=125)),
                ('zip_code', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('commission_rate', models.IntegerField(blank=True, default=50, help_text=b'Commmission as charged by the agency in %')),
                ('website', models.URLField(blank=True, max_length=250)),
                ('contact_person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
