# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170109_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(blank=True, default=b'DE', on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
    ]
