# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20170109_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='in_acquisition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='in_acquisition',
            field=models.BooleanField(default=False),
        ),
    ]
