# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20170110_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_variant_price_per_country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('rec_gross_sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name=b'Recommended default gross sale price in the currency of the country')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Product variant price per country',
                'verbose_name_plural': 'Product variant prices per country',
            },
        ),
    ]
