# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_product_variant_rec_gross_sale_price_by_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='rec_gross_sale_price_by_country',
        ),
        migrations.AddField(
            model_name='product_variant_price_per_country',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Product_variant'),
            preserve_default=False,
        ),
    ]
