# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170110_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_variant_price_per_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('rec_gross_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name=b'Recommended gross sale price in this store and in the currency of the stores country')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product_variant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Product variant price per store',
                'verbose_name_plural': 'Product variant prices per store',
            },
        ),
    ]
