# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_product_variant_price_per_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, upload_to=b'images')),
                ('contact_person', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=125)),
                ('zip_code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=250)),
                ('banking_account_recipient', models.CharField(blank=True, max_length=100)),
                ('banking_account_bank', models.CharField(blank=True, max_length=100)),
                ('banking_account_iban', models.CharField(blank=True, max_length=100)),
                ('banking_account_bic', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name=b'Tax number')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name=b'VAT number')),
                ('eori_number', models.CharField(blank=True, help_text=b'Economic Operators\xe2\x80\x99 Registration and Identification number used in customs declarations', max_length=100, verbose_name=b'EORI number')),
                ('country', models.ForeignKey(blank=True, default=b'DE', on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
            options={
                'verbose_name': 'Core_data',
                'verbose_name_plural': 'Core data',
            },
        ),
    ]
