# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_core_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Product_move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('move_date', models.DateTimeField(default=datetime.datetime.now)),
                ('move_type', models.CharField(choices=[(b'moved_to_store', b'Moved to store'), (b'non_saleable', b'Marked as non-saleable')], max_length=20)),
                ('remove_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Store')),
            ],
            options={
                'ordering': ('move_date',),
                'verbose_name': 'Product move',
                'verbose_name_plural': 'Product moves',
            },
        ),
        migrations.CreateModel(
            name='Product_variant_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Listing')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product_variant')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Product variant quantity',
                'verbose_name_plural': 'Product variant quantities',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='product_move_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product_move'),
        ),
    ]
