# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20170115_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant_quantity',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='product_variant_quantity',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='listing',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Product_variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Product_variant_quantity',
        ),
    ]
