# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20170115_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_move',
            name='move_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moveto', to='api.Store'),
            preserve_default=False,
        ),
    ]
