# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20170115_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('sale_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sale_type', models.CharField(choices=[(b'direct-sale-to-customer', b'Direct sale to customer'), (b'online-sale', b'Online sale'), (b'commission-sale', b'Commission sale'), (b'sale-to-store', b'Sale to store'), (b'sale-to-store-via-agency', b'Sale to store via agency'), (b'other', b'Other')], max_length=20)),
            ],
            options={
                'ordering': ('sale_date',),
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='agency_involved',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyinvolved', to='api.Agency'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_to_customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldtocustomer', to='api.Customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_to_store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldtostore', to='api.Store'),
        ),
    ]
