# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20170115_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_move_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product_move'),
        ),
        migrations.AlterField(
            model_name='product_move',
            name='move_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moveto', to='api.Store'),
        ),
        migrations.AlterField(
            model_name='product_move',
            name='remove_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Store'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agency_involved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencyinvolved', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldtocustomer', to='api.Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_to_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldtostore', to='api.Store'),
        ),
    ]
