# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20170115_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product_variant'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
